version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysqlServiceHost
    network_mode: bridge
    ports:
    - "3306:3306"
    #restart: always
    restart: on-failure
    volumes:
    - ./mysql:/var/lib/mysql
    - ./my.cnf:/etc/mysql/conf.d/my.cnf
    - ./mysql/init:/docker-entrypoint-initdb.d/
    - ./shop.sql:/docker-entrypoint-initdb.d/shop.sql
    environment:
    - MYSQL_ROOT_PASSWORD=a123456
    - MYSQL_USER=root
    - MYSQL_PASSWORD=a123456
    - MYSQL_DATABASE=shop
  redis:
    image: redis:3
    container_name: redis
    hostname: redisServiceHost
    network_mode: bridge
    restart: on-failure
    ports:
    - "6379:6379"

  golang:
    build: .
    restart: on-failure
    network_mode: bridge
    ports:
    - "8080:8080"
    links:
    - mysql
    - redis
    volumes:
    - /Users/mac/go/src/gitee.com/shirdonl/LeastMall:/go
    tty: true